apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  namespace: argocd
spec:
  project: default
  source:
    chart: dagster
    repoURL: https://dagster-io.github.io/helm
    valuesFile: values/dagster.yaml
    targetRevision: 1.7.14
    helm:
      releaseName: dagster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: databases
  syncPolicy:
    automated:
      selfHeal: true
      prune: true