apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: 'https://charts.bitnami.com/bitnami'
    valuesFile: values/prometheus.yaml
    targetRevision: 1.3.12
    helm:
      releaseName: prometheus
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true